
pipeline {
    agent any

    environment {
        ARTEFACT_NAME = "${WORKSPACE}/target/WebGoat-${BUILD_VERSION}.war"
        DEV_REPO = 'staging-dev'
        TAG_FILE = "${WORKSPACE}/tag.json"
        IQ_APP_NAME = "webgoat2"
        IQ_URL = "http://localhost:8070"
        IQ_STAGE = "build"
        IQ_CLI = "/opt/nxiq/nexus-iq-cli"
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -Dproject.version=$BUILD_VERSION -Dmaven.test.failure.ignore clean package'
            }
            post {
                success {
                    echo 'Now archiving...'
                    archiveArtifacts artifacts: "**/target/*.war"
                }
            }
        }

        stage('Get Commit hash'){
            steps {
                // export COMMIT=$(git rev-parse HEAD); echo "{\"commitHash\": \"${COMMIT}\"}" > metadata.json
                //GIT_COMMIT_HASH = sh (script: "git log -n 1 --pretty=format:'%H'", returnStdout: true)
                //echo "Git commit hash: ${GIT_COMMIT_HASH}"
                echo "Git commit hash: ${GIT_COMMIT}"
            }
        } 

        stage('Nexus IQ Scan'){
            steps {
                sh 'java -jar ${IQ_CLI} -i ${IQ_APP_NAME} -s ${IQ_URL} -a admin:admin123 -t ${IQ_STAGE} ${ARTEFACT_NAME}'
            }
        }        
    }
}

